name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Anything:
    runs-on: ubuntu-latest

    steps:
    - name: check all code
      uses: actions/checkout@v2

    - name: Setting up node environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: testing dependencies
      run: npm install

    - name: Runing test
      run: npm test
